theme: jekyll-theme-minimal
title: Ericka B. Smith
logo: images/thumbnail.jpg
description: Welcome! I'm a student in the statistics master's program at Oregon State University. I graduate in March 2021 and I'm actively looking for data science roles that are remote or in Oregon. 
email: smith.ericka.b@gmail.com
github_username: erickabsmith
