theme: jekyll-theme-dinky
title: Ericka B. Smith
logo: images/thumbnail.jpg
description: I'm a statistician looking to share some of my excitement for data exploration and analysis.
google_analytics: UA-191728066-1
