theme: jekyll-theme-dinky
title: Ericka Howard
logo: images/thumbnail.jpg
description: I'm a data scientist looking to share some of my excitement for data exploration and analysis. I have extensive experience with insurance, sales, and environmental data. 
