theme: jekyll-theme-midnight
title: Ericka B. Smith
description:

I'm currently working on my M.S. in Statistics at Oregon State University.

You can check out some of my work here - 
https://erickabsmith.shinyapps.io/catch-data/
https://jimmylovestea.shinyapps.io/datadash/

