theme: jekyll-theme-minima
title: Ericka B. Smith
logo: images/thumbnail.jpg
description: Welcome! My name is Ericka Smith and I'm a master's student in the Statistics Department at Oregon State University. My projected graduation is March 2021 and I'm currently looking for positions where I can use data to optimize processes and solve problems. 
