theme: jekyll-theme-minimal
title: Ericka B. Smith
logo: images/thumbnail.jpg
description: Welcome! I'm a student about to graduate (March 2021!) with my M.S. in Statistics from Oregon State University. 
